/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package by.dma;

public class SparkConsoleApp {
    public static void main(String[] args) {

        new SparkBaseDemo().execute();
        //new SparkExperiments().testMaxLength();
    }
}
