/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package by.dma;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class SparkAppTest {
    @Test void appHasAGreeting() {
        SparkConsoleApp classUnderTest = new SparkConsoleApp();
        assertNotNull(classUnderTest);
    }
}
